// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("MyProvider2.DesignTime")>]
[<assembly: AssemblyProductAttribute("MyProvider2")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing MyProvider2.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "MyProvider2.DesignTime"
    let [<Literal>] AssemblyProduct = "MyProvider2"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing MyProvider2."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
